// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFpDpV0GJLCSsTx7YQQXQGHqK6teCLhlg',
    appId: '1:369796753935:android:907f88d7991aca64c7117a',
    messagingSenderId: '369796753935',
    projectId: 'eventsmobile-2c4b1',
    storageBucket: 'eventsmobile-2c4b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNtYxFjxooeZyf6RQ_7y_GDWq38D0MTHs',
    appId: '1:369796753935:ios:9b7ced432cc9bdf4c7117a',
    messagingSenderId: '369796753935',
    projectId: 'eventsmobile-2c4b1',
    storageBucket: 'eventsmobile-2c4b1.firebasestorage.app',
    androidClientId: '369796753935-okqeaehfbkm18f9ul07dvq10m2inmgau.apps.googleusercontent.com',
    iosClientId: '369796753935-70td8p55uhljav5tmcgb2vuchcfv76fq.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventMobileApp',
  );

}